# Generated by Django 2.0.4 on 2018-04-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='emm', max_length=10)),
                ('passwd', models.CharField(default='123', max_length=10)),
            ],
        ),
    ]
